datasources:
 - name: InfluxDB
   type: "influxdb"
   typeName: "InfluxDB"
   typeLogoUrl: "public/app/plugins/datasource/influxdb/img/influxdb_logo.svg"
   access: proxy
   orgId: 1
   url: http://127.0.0.1:8086
   password: "wlanpi_1963"
   user: "wlanpi"
   database: "wlanpi"
   basicAuth: False
   isDefault: true
   jsonData:
     httpMode: "GET"
     version: "InfluxQL"
   version: 1
   editable: true
   
